INSERT INTO fleuriste.address (id, number, roadtype, roadname, additionaladdress, postalcode, city_id, numberaddition) VALUES (1, 9, 'parc', 'du donjon', '1er etage gauche', '91700', 91549, null);
INSERT INTO fleuriste.address (id, number, roadtype, roadname, additionaladdress, postalcode, city_id, numberaddition) VALUES (2, 9, 'parc', 'du donjon', '1er etage gauche', '91700', 91235, null);
INSERT INTO fleuriste.address (id, number, roadtype, roadname, additionaladdress, postalcode, city_id, numberaddition) VALUES (3, 9, 'parc', 'du donjon', '1er etage gauche', '91000', 91228, null);
INSERT INTO fleuriste.address (id, number, roadtype, roadname, additionaladdress, postalcode, city_id, numberaddition) VALUES (4, 21, 'avenue', 'des hetres', '', '91170', 91687, null);
INSERT INTO fleuriste.address (id, number, roadtype, roadname, additionaladdress, postalcode, city_id, numberaddition) VALUES (5, 21, 'avenue', 'des hetres', '', '91170', 0, null);
INSERT INTO fleuriste.person (id, name, firstName, birthday, email, password, photopath, banned, deleted, enabled, confirmation_token, password_requested_at, creationdate, rights, address_id, username, username_canonical, email_canonical, salt, plain_password, last_login, roles) VALUES (1, null, null, null, 'bourdin.maurice@gmail.com', '$2y$13$lxjHAdEfOvQgJAVhEjGEXusjRKTExXTTCMYeAwdIIT8bEclXfGXIi', null, 0, 0, 1, null, null, null, 4, 1, 'mbourdin', 'mbourdin', 'bourdin.maurice@gmail.com', null, null, '2019-05-13 13:13:03', 'a:1:{i:0;s:14:"ROLE_ACC_ADMIN";}');
INSERT INTO fleuriste.person (id, name, firstName, birthday, email, password, photopath, banned, deleted, enabled, confirmation_token, password_requested_at, creationdate, rights, address_id, username, username_canonical, email_canonical, salt, plain_password, last_login, roles) VALUES (2, null, null, null, 'maurice@bourdin.biz', '$2y$13$A.YpXcAic6.gwuJWJANqKuq7MqbucYoaBzql7mADYt5M9mlDcAVNu', null, 0, 0, 1, null, null, null, 6, null, 'mbourdin2', 'mbourdin2', 'maurice@bourdin.biz', null, null, '2019-05-13 13:29:53', 'a:2:{i:0;s:10:"ROLE_ADMIN";i:1;s:14:"ROLE_ACC_ADMIN";}');
INSERT INTO fleuriste.persons_addresses (person_id, address_id) VALUES (1, 5);
INSERT INTO fleuriste.product (id, photopath, price, description, name, active, product_type_id) VALUES (1, '871-14.jpg', 1, 'x', 'test', 1, null);
INSERT INTO fleuriste.product (id, photopath, price, description, name, active, product_type_id) VALUES (2, 'LogoUniflors.jpg', 1, 'x', 'test', 1, null);
INSERT INTO fleuriste.product (id, photopath, price, description, name, active, product_type_id) VALUES (3, '871-14.jpg', 1, 'x', 'test', 1, null);
INSERT INTO fleuriste.product (id, photopath, price, description, name, active, product_type_id) VALUES (4, 'Chrysanthemum.jpg', 9, 'Q', 'Q', 1, null);
INSERT INTO fleuriste.product_type (id, name, photopath, active) VALUES (1, 'Orchidées', 'doom.jpg', 1);
INSERT INTO fleuriste.products_types (product_id, product_type_id) VALUES (1, 1);
INSERT INTO fleuriste.sale (id, onlinepay, paid, discount, date, person_id, validated, contact, recipient, address_id) VALUES (1, 1, 0, 0, '2019-05-13 00:00:00', 1, 1, 'co', 'co', 1);
INSERT INTO fleuriste.sale (id, onlinepay, paid, discount, date, person_id, validated, contact, recipient, address_id) VALUES (2, 1, 0, 0, null, 1, 0, null, null, null);
INSERT INTO fleuriste.sale (id, onlinepay, paid, discount, date, person_id, validated, contact, recipient, address_id) VALUES (3, 1, 0, 0, null, 1, 0, null, null, null);
INSERT INTO fleuriste.sale_product_content (sale_id, product_id, quantity, pricewhenbought, id) VALUES (1, 1, 3, 1, 1);
INSERT INTO fleuriste.sale_product_content (sale_id, product_id, quantity, pricewhenbought, id) VALUES (2, 2, 1, 1, 2);
INSERT INTO fleuriste.sale_product_content (sale_id, product_id, quantity, pricewhenbought, id) VALUES (3, 3, 1, 1, 3);
INSERT INTO fleuriste.service (id, photopath, price, description, name, active) VALUES (1, null, 600, 'TEST', 'TestService', 0);
